// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	battle.proto

It has these top-level messages:
	Enter
	Position
	PlayerInfo
	NpcInfo
	WeaponInfo
	BattleStart
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_enter MsgType = 0
)

var MsgType_name = map[int32]string{
	0: "enter",
}
var MsgType_value = map[string]int32{
	"enter": 0,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Enter struct {
	PlayerId         *int32 `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	RoomId           *int32 `protobuf:"varint,2,opt,name=roomId" json:"roomId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Enter) Reset()                    { *m = Enter{} }
func (m *Enter) String() string            { return proto.CompactTextString(m) }
func (*Enter) ProtoMessage()               {}
func (*Enter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Enter) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *Enter) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

type Position struct {
	X                *int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type PlayerInfo struct {
	Id               *int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pos              *Position `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerInfo) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

type NpcInfo struct {
	Id               *int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pos              *Position `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *NpcInfo) Reset()                    { *m = NpcInfo{} }
func (m *NpcInfo) String() string            { return proto.CompactTextString(m) }
func (*NpcInfo) ProtoMessage()               {}
func (*NpcInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NpcInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *NpcInfo) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

type WeaponInfo struct {
	Id               *int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pos              *Position `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *WeaponInfo) Reset()                    { *m = WeaponInfo{} }
func (m *WeaponInfo) String() string            { return proto.CompactTextString(m) }
func (*WeaponInfo) ProtoMessage()               {}
func (*WeaponInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WeaponInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WeaponInfo) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

type BattleStart struct {
	Players          []*PlayerInfo `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	Npcs             []*NpcInfo    `protobuf:"bytes,2,rep,name=npcs" json:"npcs,omitempty"`
	Weapons          []*WeaponInfo `protobuf:"bytes,3,rep,name=weapons" json:"weapons,omitempty"`
	Seed             *int32        `protobuf:"varint,4,opt,name=seed" json:"seed,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *BattleStart) Reset()                    { *m = BattleStart{} }
func (m *BattleStart) String() string            { return proto.CompactTextString(m) }
func (*BattleStart) ProtoMessage()               {}
func (*BattleStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BattleStart) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *BattleStart) GetNpcs() []*NpcInfo {
	if m != nil {
		return m.Npcs
	}
	return nil
}

func (m *BattleStart) GetWeapons() []*WeaponInfo {
	if m != nil {
		return m.Weapons
	}
	return nil
}

func (m *BattleStart) GetSeed() int32 {
	if m != nil && m.Seed != nil {
		return *m.Seed
	}
	return 0
}

func init() {
	proto.RegisterType((*Enter)(nil), "pb.Enter")
	proto.RegisterType((*Position)(nil), "pb.Position")
	proto.RegisterType((*PlayerInfo)(nil), "pb.PlayerInfo")
	proto.RegisterType((*NpcInfo)(nil), "pb.NpcInfo")
	proto.RegisterType((*WeaponInfo)(nil), "pb.WeaponInfo")
	proto.RegisterType((*BattleStart)(nil), "pb.BattleStart")
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
}

func init() { proto.RegisterFile("battle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbd, 0x6a, 0xc3, 0x30,
	0x14, 0x85, 0x2b, 0xff, 0xd4, 0xf1, 0xb1, 0x09, 0x41, 0x74, 0x50, 0xa6, 0x18, 0x4f, 0x69, 0x07,
	0x53, 0x92, 0x37, 0x28, 0x74, 0xc8, 0xd0, 0x12, 0x68, 0xa1, 0xb3, 0x1d, 0xab, 0xc5, 0x90, 0x4a,
	0x17, 0x49, 0xd0, 0xf8, 0xed, 0x8b, 0x9c, 0x98, 0x64, 0xf5, 0x28, 0xee, 0x39, 0x9f, 0xbe, 0x7b,
	0x91, 0x37, 0xb5, 0x73, 0x47, 0x59, 0x91, 0xd1, 0x4e, 0xf3, 0x80, 0x9a, 0xf2, 0x11, 0xf1, 0xab,
	0x72, 0xd2, 0xf0, 0x05, 0x66, 0x74, 0xac, 0x7b, 0x69, 0x76, 0xad, 0x60, 0x05, 0x5b, 0xc7, 0x7c,
	0x8e, 0x7b, 0xa3, 0xf5, 0xef, 0xae, 0x15, 0x81, 0x7f, 0x97, 0x05, 0x66, 0x7b, 0x6d, 0x3b, 0xd7,
	0x69, 0xc5, 0x53, 0xb0, 0xd3, 0x25, 0x96, 0x82, 0xf5, 0x97, 0xc4, 0x16, 0xd8, 0x9f, 0x19, 0xea,
	0x5b, 0x73, 0x20, 0xe8, 0x46, 0xd6, 0x12, 0x21, 0x69, 0x3b, 0xc4, 0xb2, 0x4d, 0x5e, 0x51, 0x53,
	0x8d, 0xa8, 0xf2, 0x19, 0xc9, 0x3b, 0x1d, 0xa6, 0x34, 0xb6, 0xc0, 0x97, 0xac, 0x49, 0xab, 0x29,
	0xa5, 0x13, 0xb2, 0x97, 0x61, 0xf9, 0x0f, 0x57, 0x1b, 0xc7, 0x57, 0x48, 0xce, 0xeb, 0x5a, 0xc1,
	0x8a, 0x70, 0x9d, 0x6d, 0xe6, 0x43, 0xfa, 0x6a, 0xbf, 0x44, 0xa4, 0xe8, 0xe0, 0x59, 0x7e, 0x9a,
	0xf9, 0xe9, 0xa8, 0xb9, 0x42, 0xf2, 0x37, 0xfc, 0x6f, 0x45, 0x78, 0xed, 0xde, 0x28, 0xe5, 0x88,
	0xac, 0x94, 0xad, 0x88, 0xbc, 0xd4, 0xd3, 0x03, 0x92, 0x37, 0xfb, 0xf3, 0xd9, 0x93, 0xe4, 0x29,
	0x62, 0xe9, 0xaf, 0xbd, 0xb8, 0xfb, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x34, 0x56, 0x87, 0xcc, 0x8b,
	0x01, 0x00, 0x00,
}
